### ISSUE TITLE
--

### ISSUE THREAD

**Issue by golddotasksquestions** [Arnklit/WaterGenGodotDemo#2]
Depending on how murky a river is, if it is magical or realistic natural, fast or slow moving ... the falloff of the clarity property would be great if adjustable and not linear.

**Comment by Arnklit** [comment]
Hmm not sure why you closed this. I thought it was an interesting idea. My plan though is to move over to a realistic scattering shader instead, so this that will change all these controls as well.

**Comment by golddotasksquestions** [comment]
I closed it because this is the Demo, I made the same issue request over at the Addon instead. :)
