### ISSUE TITLE
"Fold" I can't seem to iron out

### ISSUE THREAD

**Issue by golddotasksquestions** [Arnklit/WaterGenGodotDemo#3]
https://user-images.githubusercontent.com/47016402/103316574-3ba95600-4a29-11eb-889c-548ee6c11ae2.mp4

I checked the geometry (wireframe view) and it seemed fine. No idea what is causing this, but it immediately caught my attention when I first opened the scene as this crease or fold looks rather "synthetic" and digital.

**Comment by Arnklit** [comment]
This is actually a general issue in the tool that I haven't fixed yet, but am aware off. The problem comes from the UV2 layout which has seams there. I might have to add margins to the entire UV2 layout and textures to fix it, but I'm still looking to see if I can fix it without doing that.

**Comment by Arnklit** [comment]
This has now been fixed in 0.2.1.

**Comment by golddotasksquestions** [comment]
What was the cause for this?

**Comment by Arnklit** [comment]
It's a bit complicated to explain, but the UV2s are used for the flow, foam, distance and pressure textures which have a grid like layout that causes there to be seams. To fix it I had to leave some margins on the texture and sample from a central area inside the margins.
